version: '3.8'

services:
  web:
    container_name: imahima_web_dev_alone
    build:
      context: ./imahima
      dockerfile: Dockerfile.dev
    volumes:
      - ./imahima:/usr/src/app/
    ports:
      - '8080:8080'
    environment:
      - VUE_APP_API_ENDPOINT=http://localhost:8000/